# Generated by Django 4.0.5 on 2022-07-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('curso', models.IntegerField(null=True)),
                ('nota', models.FloatField(default=0)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.ManyToManyField(to='webapp.estudiante')),
                ('Profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField(max_length=100)),
                ('Asignatura', models.ManyToManyField(to='webapp.asignatura')),
                ('Estudiante', models.ManyToManyField(to='webapp.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='Profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.profesor'),
        ),
    ]
