# Generated by Django 4.0.3 on 2022-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_asignatura_profesor_asignatura_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='Asignatura',
            new_name='asignatura',
        ),
        migrations.RenameField(
            model_name='calificaciones',
            old_name='Estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='estudianteprofesor',
            old_name='Estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='estudianteprofesor',
            old_name='Profesor',
            new_name='profesor',
        ),
        migrations.AddField(
            model_name='estudianteprofesor',
            name='curso',
            field=models.CharField(default='Palomitas', max_length=10),
        ),
    ]
