# Generated by Django 4.0.3 on 2022-07-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_asignatura_calificaciones_asignatura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteProfesor',
        ),
    ]
